"""empty message

Revision ID: 2662a00d093
Revises: None
Create Date: 2014-10-16 14:52:36.196087

"""

# revision identifiers, used by Alembic.
revision = '2662a00d093'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
