"""empty message

Revision ID: 297af4e01970
Revises: 2662a00d093
Create Date: 2014-10-16 14:56:36.030005

"""

# revision identifiers, used by Alembic.
revision = '297af4e01970'
down_revision = '2662a00d093'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
